// <auto-generated />
using System;
using Gestao_veiculos.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Veiculo_gestao.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Gestao_veiculos.Models.PasswordResetToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("expires_at");

                    b.Property<int>("Id_usuario")
                        .HasColumnType("int")
                        .HasColumnName("id_usuario");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)")
                        .HasColumnName("token");

                    b.Property<bool>("Used")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(false)
                        .HasColumnName("used");

                    b.HasKey("Id");

                    b.HasIndex("Id_usuario");

                    b.HasIndex("Token")
                        .IsUnique();

                    b.ToTable("password_reset_token", (string)null);
                });

            modelBuilder.Entity("Gestao_veiculos.Models.Proposta", b =>
                {
                    b.Property<int>("Id_proposta")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_proposta");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id_proposta"));

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("data_criacao");

                    b.Property<int>("Id_proprietario")
                        .HasColumnType("int")
                        .HasColumnName("id_proprietario");

                    b.Property<int>("Id_usuario")
                        .HasColumnType("int")
                        .HasColumnName("id_usuario");

                    b.Property<int>("Id_veiculo")
                        .HasColumnType("int")
                        .HasColumnName("id_veiculo");

                    b.Property<string>("SessaoProposta")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("varchar(25)")
                        .HasColumnName("cod_proposta");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("status_proposta");

                    b.HasKey("Id_proposta");

                    b.HasIndex("Id_proprietario");

                    b.HasIndex("Id_usuario");

                    b.HasIndex("Id_veiculo");

                    b.ToTable("proposta", (string)null);
                });

            modelBuilder.Entity("Gestao_veiculos.Models.Proprietario", b =>
                {
                    b.Property<int>("Id_proprietario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_proprietario");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id_proprietario"));

                    b.Property<string>("Cpf")
                        .IsRequired()
                        .HasMaxLength(14)
                        .HasColumnType("varchar(14)")
                        .HasColumnName("cpf_cnpj");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("email");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("varchar(80)")
                        .HasColumnName("nome");

                    b.Property<string>("Telefone")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("varchar(15)")
                        .HasColumnName("telefone");

                    b.HasKey("Id_proprietario");

                    b.HasIndex("Cpf")
                        .IsUnique();

                    b.ToTable("proprietario", (string)null);
                });

            modelBuilder.Entity("Gestao_veiculos.Models.Termo", b =>
                {
                    b.Property<int>("Id_termo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_termo");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id_termo"));

                    b.Property<DateTime?>("DataAssinatura")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("data_assinatura");

                    b.Property<DateTime>("DataEnvio")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("data_envio");

                    b.Property<int>("Id_proposta")
                        .HasColumnType("int")
                        .HasColumnName("id_proposta");

                    b.Property<string>("NumeroTermo")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("varchar(25)")
                        .HasColumnName("numero_termo");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("status_termo");

                    b.HasKey("Id_termo");

                    b.HasIndex("Id_proposta");

                    b.ToTable("termo", (string)null);
                });

            modelBuilder.Entity("Gestao_veiculos.Models.Usuario", b =>
                {
                    b.Property<int>("Id_usuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_usuario");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id_usuario"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("email");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("varchar(80)")
                        .HasColumnName("nome");

                    b.Property<string>("Role")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasDefaultValue("User")
                        .HasColumnName("role");

                    b.Property<string>("Senha")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("senha");

                    b.HasKey("Id_usuario");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("usuario", (string)null);
                });

            modelBuilder.Entity("Gestao_veiculos.Models.Veiculo", b =>
                {
                    b.Property<int>("Id_veiculo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_veiculo");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id_veiculo"));

                    b.Property<int>("AnoFab")
                        .HasColumnType("int")
                        .HasColumnName("ano_fabricacao");

                    b.Property<int>("AnoMod")
                        .HasColumnType("int")
                        .HasColumnName("ano_modelo");

                    b.Property<string>("Chassi")
                        .IsRequired()
                        .HasMaxLength(17)
                        .HasColumnType("varchar(17)")
                        .HasColumnName("chassi");

                    b.Property<string>("Cor")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("cor");

                    b.Property<string>("Marca")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("marca");

                    b.Property<string>("Modelo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("modelo");

                    b.Property<string>("Placa")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("placa");

                    b.Property<string>("Renavam")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("varchar(11)")
                        .HasColumnName("renavam");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("status_veiculo");

                    b.HasKey("Id_veiculo");

                    b.HasIndex("Chassi")
                        .IsUnique();

                    b.HasIndex("Placa")
                        .IsUnique();

                    b.HasIndex("Renavam")
                        .IsUnique();

                    b.ToTable("veiculo", (string)null);
                });

            modelBuilder.Entity("Gestao_veiculos.Models.Vistoria", b =>
                {
                    b.Property<int>("Id_vistoria")
                        .HasColumnType("int")
                        .HasColumnName("id_vistoria");

                    b.Property<DateTime?>("DataConclusao")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("data_conclusao");

                    b.Property<DateTime?>("DataInicio")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("data_inicio");

                    b.Property<DateTime>("DataSolicitacao")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("data_solicitacao");

                    b.Property<int>("Id_proposta")
                        .HasColumnType("int")
                        .HasColumnName("id_proposta");

                    b.Property<int>("Id_usuario")
                        .HasColumnType("int")
                        .HasColumnName("id_usuario_responsavel");

                    b.Property<string>("Observacoes")
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)")
                        .HasColumnName("observacoes");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("status_vistoria");

                    b.HasKey("Id_vistoria");

                    b.HasIndex("Id_proposta");

                    b.HasIndex("Id_usuario");

                    b.ToTable("vistoria", (string)null);
                });

            modelBuilder.Entity("Gestao_veiculos.Models.VistoriaFoto", b =>
                {
                    b.Property<int>("Id_foto")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_foto");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id_foto"));

                    b.Property<int>("Id_vistoria")
                        .HasColumnType("int")
                        .HasColumnName("id_vistoria");

                    b.Property<string>("Slot")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("slot");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("url");

                    b.Property<string>("Verdict")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("verdict");

                    b.HasKey("Id_foto");

                    b.HasIndex("Id_vistoria", "Slot")
                        .IsUnique();

                    b.ToTable("vistoria_foto", (string)null);
                });

            modelBuilder.Entity("Gestao_veiculos.Models.PasswordResetToken", b =>
                {
                    b.HasOne("Gestao_veiculos.Models.Usuario", null)
                        .WithMany()
                        .HasForeignKey("Id_usuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Gestao_veiculos.Models.Proposta", b =>
                {
                    b.HasOne("Gestao_veiculos.Models.Proprietario", null)
                        .WithMany()
                        .HasForeignKey("Id_proprietario")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Gestao_veiculos.Models.Usuario", null)
                        .WithMany()
                        .HasForeignKey("Id_usuario")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Gestao_veiculos.Models.Veiculo", null)
                        .WithMany()
                        .HasForeignKey("Id_veiculo")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Gestao_veiculos.Models.Termo", b =>
                {
                    b.HasOne("Gestao_veiculos.Models.Proposta", null)
                        .WithMany()
                        .HasForeignKey("Id_proposta")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Gestao_veiculos.Models.Vistoria", b =>
                {
                    b.HasOne("Gestao_veiculos.Models.Proposta", null)
                        .WithMany()
                        .HasForeignKey("Id_proposta")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Gestao_veiculos.Models.Usuario", null)
                        .WithMany()
                        .HasForeignKey("Id_usuario")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Gestao_veiculos.Models.VistoriaFoto", b =>
                {
                    b.HasOne("Gestao_veiculos.Models.Vistoria", null)
                        .WithMany()
                        .HasForeignKey("Id_vistoria")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
